### ISSUE TITLE
Hi-Ether Meetup #6 Tokyo を開催する / 2018年7月19日 / SmartNews

### ISSUE THREAD

**Issue by takei-shg** [hi-ether/community#10]
# TODO

## 早めにやること
- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [x] LT スピーカーを決める
- [x] タイムテーブルをつくる
- [x] techplayでLPを用意
- [x] 参加者費用を決定(今回はSmartNewsで負担)
- [x] 参加登録を開始する

## 開催x日前
- [x] 参加者人数を把握する
- [x] 食べもの・飲みものを手配する
- [x] 食べ物/飲み物の受け取り方を決める
- [x] 会場の「ゴミの捨て方」を確認して備えておく
- [x] ~~会場までの道案内を印刷~~ 当日Slackにて入り口の写真を共有、２Fまで来てもらう
- [x] 前日〜当日あたりに諸情報を含めたリマインドをする
- [x] 担当最終決定
- [x] 発表会場、設備点検

## 当日
- [x] 開催する！
- [x] 会場設営(椅子、電源タップ、受付机)
- [x] 受付にてtechplayからDLした参加者一覧csvを編集できるPCを用意
- [x] マイクチェック
- [x] 会場までの道案内を掲載
- [x] 収支報告をする

# 担当

- 会場予約 1 人 : @takei-shg
- コンテンツ委員 1〜2 人 :
- 受付 3 人 : @yaggytter @kooooohe @areph
- 会計 1 人 : @takei-shg
- 司会 1 人 : @takei-shg
- 撮影・配信 0〜2 人 : @kazush-m 
- 飲食手配 1〜2 人 : @takei-shg
- タイムキーパー 1 人 : (受付の中からどなたかにお願い)
- イベントページ準備 1 人 : @takei-shg

**Comment by kurotaky** [comment]
Hi-Ether Meetup #6 で発表予定の @kurotaky です✋よろしくお願いします〜 😄

**Comment by takei-shg** [comment]
開催を7/19(木)に決定しました！イベントページを早めに上げます〜

**Comment by yaggytter** [comment]
今回も、受付はもちろんのこと、もろもろお手伝いさせていただきたく存じます！

**Comment by takei-shg** [comment]
ありがとうございます！

**Comment by kooooohe** [comment]
私ももろもろお手伝いさせていただきます！ :)

**Comment by takei-shg** [comment]
@yaggytter @kooooohe @areph
お手伝い表明ありがとうございます！当日できれば18:30頃にお越しいただけますでしょうか。
開場前に以下をお手伝いいただけますでしょうか。
- 会場設営 (椅子出し + 電源タップ配置)
- 受付セッティング

**Comment by kazush-m** [comment]
撮影・配信 @kazush-m でお願いいたします。一時間くらい前に入らせていただけますと大変たすかります。

**Comment by takei-shg** [comment]
@kazush-m よろしくおねがいします！トーク開始1時間前の18:30ということで大丈夫でしょうか？それより前でも対応できますので。

**Comment by kazush-m** [comment]
ありがとうございます！ 1830でお願いいたします。あとwi-fi 使わせていただけますと大変助かります！

**Comment by yaggytter** [comment]
@takei-shg 
承知しました！1830までに行きます！

**Comment by kazush-m** [comment]
ありがとうございます！

**Comment by june29** [comment]
運営に関わってくれたみなさん、ありがとうございました！今回も楽しい Meetup でした :heart_eyes:

https://github.com/hi-ether/community/issues/10#issue-324248252 の TODO リストがきれいに整理されていて感心です :dash: 今後はこれをもとにしてやっていくとよさそうですね〜 :relaxed:

**Comment by takei-shg** [comment]
皆様、ありがとうございました！無事終了して何よりでした。

振り返り
- ドリンク類が大量に余った。
  - 最終的に参加60名（申込時は70名)。に対してピザLサイズ12枚で完食、ビール・チューハイは96本用意してかなり余った（よなよなエールはなくなっていた）。ソフトドリンク2Lペット10本も消費は半分いかないくらいといったところ。
- カクヤスの受け取りが懇親会開始より少し遅れた。LTは飲みながらでもいい気がするのでドリンクの受け取りは１時間早めても良かった。

その他、気づいたことがある方はissue commentを残していただけると嬉しいです。
ひとまずcloseいたします〜
